### ISSUE TITLE
Post-ownership transfer updates

### ISSUE THREAD

**Issue by RobertoMachorro** [ChildRescueCoalition/express-app#2]
# Task Spec

This project previously belonged to @RobertoMachorro - ownership has now been transferred to @ChildRescueCoalition as an official open source project. The next step is to dust off some of the artifacts and references from the sources old location. While we are at it, make the code ready for sharing with the world.

# Technical Spec

This will be both an automated and manual process. The first will involve search and replace for broken links (referencing the prior repository) and the latter by scanning through the files and doing a code review.

# Approach

- [ ] SED out old links and references to new URL.
- [ ] Give a sanity check out of the old code.
- [ ] Clean up branches and dead code
